ferriskey/ferriskey

- api/src/bin/main.rs
- api/src/lib/application.rs
- api/src/lib/application/server.rs
- api/src/lib/domain/credential/service.rs
- api/src/lib/domain/mediator/service.rs
- Introduced a new `AppServer` struct to encapsulate repository and service initialization, improving code organization and readability.
- Updated the main function to utilize the new `AppServer` for service instantiation, reducing direct dependencies on individual repositories.
- Added a new `server` module to the application structure for better modularity.
> refactor: restructure application server and update main entry point

- api/src/lib/application/http/authentication/handlers/auth.rs
- api/src/lib/application/http/authentication/handlers/authentificate.rs
- api/src/lib/application/http/authentication/handlers/token.rs
- api/src/lib/application/http/authentication/router.rs
- api/src/lib/application/http/client/handlers/create_client.rs
- api/src/lib/application/http/client/router.rs
- api/src/lib/application/http/realm/handlers/create_realm.rs
- api/src/lib/application/http/realm/handlers/delete_realm.rs
- api/src/lib/application/http/realm/handlers/fetch_realm.rs
- api/src/lib/application/http/realm/handlers/get_realm.rs
- api/src/lib/application/http/realm/handlers/update_realm.rs
- api/src/lib/application/http/realm/handlers/update_realm_setting.rs
- api/src/lib/application/http/realm/router.rs
- api/src/lib/application/http/server/app_state.rs
- api/src/lib/application/http/server/http_server.rs
- api/src/lib/application/http/user/handlers/reset_password.rs
- api/src/lib/application/http/user/router.rs
- Updated authentication and client routes to utilize a shared AppState for dependency injection, enhancing code clarity and maintainability.
- Refactored route handlers to accept AppState instead of individual service dependencies, streamlining the code structure.
- Removed unnecessary generics from route functions, simplifying the function signatures and improving readability.
- Adjusted imports across various modules to reflect the new AppState structure, ensuring consistency throughout the application.
> refactor: simplify authentication and client routes by using AppState

- api/src/lib/domain/client/services/client_service.rs
> fix: update service account username format to use client name instead id

- .gitignore
- api/.sqlx/query-2554dfa89b2a1371b204e9e9b96b0d2a68b59fb700f1baeea3a8b985c6834b3b.json
- api/.sqlx/query-2aec38ff09d6f4d319a42451deaafa0e2a23801c6065853dc1071d7d2ef0b84a.json
- api/migrations/20250408144948_redirect_uris.down.sql
- api/migrations/20250408144948_redirect_uris.up.sql
- api/src/bin/main.rs
- api/src/lib/application/http/client/errors.rs
- api/src/lib/application/http/client/handlers.rs
- api/src/lib/application/http/client/handlers/create_client.rs
- api/src/lib/application/http/client/handlers/create_redirect_uri.rs
- api/src/lib/application/http/client/router.rs
- api/src/lib/application/http/client/validators.rs
- api/src/lib/application/http/server/app_state.rs
- api/src/lib/application/http/server/http_server.rs
- api/src/lib/application/server.rs
- api/src/lib/domain/authentication/grant_type_strategies/refresh_token_strategy.rs
- api/src/lib/domain/client/entities.rs
- api/src/lib/domain/client/entities/error.rs
- api/src/lib/domain/client/entities/redirect_uri.rs
- api/src/lib/domain/client/entities/redirect_uri_error.rs
- api/src/lib/domain/client/ports.rs
- api/src/lib/domain/client/ports/redirect_uri_repository.rs
- api/src/lib/domain/client/ports/redirect_uri_service.rs
- api/src/lib/domain/client/services.rs
- api/src/lib/domain/client/services/redirect_uri_service.rs
- api/src/lib/infrastructure/repositories.rs
- api/src/lib/infrastructure/repositories/redirect_uri_repository.rs
- front/src/App.tsx
This pull request introduces significant changes to support the management of redirect URIs in the API, including database migrations, new entities, error handling, and API routes. Additionally, it refactors some existing components to improve maintainability and extend functionality.
* **Database Migrations**:
- Added `redirect_uris` table with fields for `id`, `client_id`, `value`, `enabled`, `created_at`, and `updated_at`. Includes a foreign key constraint linking `client_id` to the `clients` table with cascading deletes (`api/migrations/20250408144948_redirect_uris.up.sql`, [api/migrations/20250408144948_redirect_uris.up.sqlR1-R14](diffhunk://#diff-dd6bf61276917438520126785e4a7e12bd52c681282975219e9c2adc751b2f69R1-R14)).
- Added a corresponding down migration to drop the …
> Feat: Creation of Client Redirect URIs

- front/src/contracts/states.interface.ts
- front/src/hooks/use-auth.ts
- front/src/pages/authentication/feature/page-callback-feature.tsx
- front/src/store/user.store.ts
This pull request introduces a token management system to support access token refreshing and expiration handling. The most significant changes include extending the `UserState` interface, implementing token refresh logic in the `useAuth` hook, and updating related components to use the new token management functionality.
* **Updated `UserState` interface**: Added `access_token`, `refresh_token`, `expiration`, and `setAuthTokens` properties to handle token storage and updates. (`front/src/contracts/states.interface.ts`, [front/src/contracts/states.interface.tsR9-R12](diffhunk://#diff-219c4bfd269e119a16105535181b44eb178986187d9955da37070bad16371a89R9-R12))
* **Implemented token refresh logic**: Introduced functions in the `useAuth` hook to decode JWTs, check token expiration, refresh …
> Enhance user authentication state management

- README.md
Update the architecture schema link
> Fix link README.md

- api/src/lib/application/http/user/handlers.rs
- api/src/lib/application/http/user/handlers/get_users.rs
- api/src/lib/application/http/user/router.rs
- api/src/lib/domain/role/entities/models.rs
- api/src/lib/domain/user/entities/model.rs
- api/src/lib/domain/user/ports/user_repository.rs
- api/src/lib/domain/user/ports/user_service.rs
- api/src/lib/domain/user/services/user_service.rs
- api/src/lib/infrastructure/repositories/user_repository.rs
- front/pnpm-lock.yaml
- front/src/App.css
- front/src/App.tsx
- front/src/api/api.interface.ts
- front/src/api/user.api.ts
- front/src/components/app-sidebar.tsx
- front/src/components/nav-main.tsx
- front/src/components/ui/badge-color.tsx
- front/src/pages/user/columns/list-client.column.tsx
- front/src/pages/user/feature/create-client-modal-feature.tsx
- front/src/pages/user/feature/page-users-overview-feature.tsx
- front/src/pages/user/page-user.tsx
- front/src/pages/user/ui/page-users-overview.tsx
- front/src/routes/sub-router/user.router.ts
This pull request introduces a new feature to manage users within realms, including backend API changes and frontend updates to integrate the feature. It also includes minor UI improvements and bug fixes. Below are the most important changes grouped by theme:
* Added a new `get_users` module in `handlers.rs` to handle fetching users by realm. This includes a new route, `GetUsersRoute`, and the `get_users` function.
* Updated `user_service.rs` and `user_repository.rs` to include a `find_by_realm_id` method for fetching users by realm ID. 
* Enhanced the `User` and `Role` models in `model.rs` with `typeshare` annotations for serialization and added new fields for compatibility with the frontend.
* Added a new `PageUser` component and integrated it into the routing structure.
* Implemented a …
> feat: add user overview and UI components

- api/src/lib/application/http/role.rs
- api/src/lib/application/http/role/errors.rs
- api/src/lib/application/http/role/handlers/get_roles.rs
- api/src/lib/application/http/role/router.rs
- api/src/lib/domain/role/entities/permission.rs
- api/src/lib/domain/role/ports.rs
- api/src/lib/domain/role/services.rs
- api/src/lib/infrastructure/repositories/role_repository.rs
- front/src/App.tsx
- front/src/api/api.interface.ts
- front/src/api/role.api.ts
- front/src/components/nav-main.tsx
- front/src/pages/role/columns/list-client.column.tsx
- front/src/pages/role/feature/create-role-modal-feature.tsx
- front/src/pages/role/feature/page-roles-overview-feature.tsx
- front/src/pages/role/page-role.tsx
- front/src/pages/role/ui/page-roles-overview.tsx
- front/src/routes/sub-router/role.router.ts
This pull request introduces a new feature for managing roles in both the backend and frontend of the application. The backend includes API endpoints and services to retrieve roles, while the frontend adds pages and components for displaying and interacting with roles. Below is a summary of the most important changes:
* Added a new `get_roles` handler to fetch roles for a specific realm, including the route definition and API documentation (`api/src/lib/application/http/role/handlers/get_roles.rs`, `api/src/lib/application/http/role/router.rs`)
* Introduced a new `errors` module in the `role` namespace to map domain errors to API errors (`api/src/lib/application/http/role/errors.rs`).
* Added a `find_by_realm_id` method to the `RoleRepository` trait and implemented it for the PostgreSQL …
> feat: implement role management features and UI components

- api/src/lib/application/http/realm/handlers/create_realm.rs
- api/src/lib/application/http/test.rs
- api/src/lib/application/server.rs
- api/src/lib/domain/realm/ports/realm_service.rs
- api/src/lib/domain/realm/services/realm_service.rs
- api/src/lib/domain/role/ports.rs
This pull request introduces significant updates to the `RealmService` and related components to support creating realms with associated users, roles, and clients. It also refactors the service layer to improve functionality and maintainability. The most important changes include the addition of the `create_realm_with_user` method, updates to the `DefaultRealmService` implementation, and modifications to related repositories and handlers.
* **Added `create_realm_with_user` method**: Introduced a new method in the `RealmService` interface and its implementation to create realms while associating users with roles and clients. This includes creating a client for the master realm, assigning permissions, and linking roles to users. (`api/src/lib/domain/realm/ports/realm_service.rs`, …
> feat: implement create realm with user functionality and update related services

- docs/src/content/docs/01-concepts/architecture.mdx
- docs/src/content/docs/01-concepts/overview.mdx
- docs/src/content/docs/01-concepts/realms.mdx
- docs/src/content/docs/welcome/installation.mdx
This pull request enhances the documentation for FerrisKey by introducing detailed descriptions of its architecture, features, and setup instructions. The changes aim to provide a clearer understanding of FerrisKey's capabilities, design principles, and deployment processes. Key updates include expanded sections on architecture, realms, and installation procedures, as well as examples and code snippets for better comprehension.
* [`docs/src/content/docs/01-concepts/architecture.mdx`](diffhunk://#diff-d1e9d9b4b3b7cb916fa2026eb170ec2a2fbf5e12f1dcaddcfefd98f273b3d216L3-R73): Expanded the architecture section to include detailed descriptions of FerrisKey's monolithic design, core modules (Identity, Authorization, Token), and technology stack. Added examples of the bitwise permission system …
> feat: enhance documentation for architecture, overview, realms, and installation sections

- api/src/lib/application/http/authentication/handlers.rs
- api/src/lib/application/http/authentication/handlers/auth.rs
- api/src/lib/application/http/authentication/handlers/get_certs.rs
- api/src/lib/application/http/authentication/router.rs
- api/src/lib/application/http/client.rs
- api/src/lib/application/http/client/handlers.rs
- api/src/lib/application/http/client/handlers/delete_client.rs
- api/src/lib/application/http/client/policies.rs
- api/src/lib/application/http/client/router.rs
- api/src/lib/domain/authentication/grant_type_strategies/password_strategy.rs
- api/src/lib/domain/authentication/service/authentication.rs
- api/src/lib/domain/client/ports/client_repository.rs
- api/src/lib/domain/client/ports/client_service.rs
- api/src/lib/domain/client/services/client_service.rs
- api/src/lib/domain/credential/services/credential_service.rs
- api/src/lib/domain/jwt/entities/jwt.rs
- api/src/lib/infrastructure/repositories/client_repository.rs
- api/src/lib/infrastructure/repositories/credential_repository.rs
- front/src/api/api.interface.ts
This pull request introduces new features for handling authentication and client management, along with several code cleanup and refactoring changes. The most significant updates include the addition of a new `get_certs` endpoint for retrieving realm-specific JWT certificates, enhancements to the `delete_client` functionality, and improvements to the `JwtKeyPair` struct to support JWK key generation.
* **New `get_certs` Endpoint**: Added a new route and handler for retrieving JWT certificates (`get_certs`), including a `GetCertsResponse` struct and the `to_jwk_key` method in `JwtKeyPair` to generate JWK keys. (`[[1]](diffhunk://#diff-c3b96501c3dccad2a66fd0f2fde5cae1641238d54e0c9d74dfdfa1b05d3c1d9eR3)`, `[[2]](diffhunk://#diff-fceeac409b388d62dea5f7025b1168651e0f7d5e240c95a36059e6e34650f089 …
> feat: get certs handler

- api/src/lib/application/http/role/handlers/get_role.rs
- api/src/lib/infrastructure/repositories/role_repository.rs
- front/src/pages/role/feature/page-role-settings-feature.tsx
- front/src/pages/role/schemas/update-role.schema.ts
- front/src/pages/role/ui/page-role-settings.tsx
This pull request introduces significant updates to both the backend and frontend components of the role management system. The backend changes focus on improving database queries and restructuring the repository logic, while the frontend changes enhance the role settings page with a more dynamic and interactive form using `react-hook-form` and schema validation with `zod`.
**Refactoring and Enhancements in Role Repository:**
* Replaced the `get_by_id` method's query to include related client data, enabling the population of client information in the returned role object.
* Reintroduced the `delete_by_id` method, previously removed, to allow deletion of roles by ID.
* Removed redundant imports and reordered them for better readability and organization.
**API Path Update:**
* Simplified …
> feat: enhance role overview

- api/src/lib/application/http/user.rs
- api/src/lib/application/http/user/handlers/get_user_roles.rs
- api/src/lib/application/http/user/policies.rs
- api/src/lib/application/http/user/policies/user_role_policies.rs
* add user_role_policies module to manage user role access
* update get_user_roles handler to incorporate permission checks using UserRolePolicy
* enhance user role retrieval logic with permission validation
> feat: implement user role policies for access control

- docs/astro.config.mjs
- docs/src/assets/css/global.css
- docs/src/lib/hooks/use-theme.ts
- docs/src/lib/layouts/BaseLayout.astro
- docs/src/pages/index.astro
* add prefetch option in astro.config.mjs for improved performance
* update global.css to include view transition animations
* refactor use-theme hook to simplify theme management
* integrate ClientRouter in BaseLayout.astro for better routing
* modify index.astro to utilize client:only for optimized rendering of components
> feat: enhance configuration and UI transitions

- api/src/lib/application/http/client/handlers.rs
- api/src/lib/application/http/client/handlers/update_client.rs
- api/src/lib/application/http/client/router.rs
- api/src/lib/application/http/client/validators.rs
- api/src/lib/application/http/user/handlers/bulk_delete_user.rs
- api/src/lib/application/http/user/handlers/delete_user.rs
- api/src/lib/domain/client/entities/dto.rs
- api/src/lib/domain/client/ports/client_repository.rs
- api/src/lib/domain/client/ports/client_service.rs
- api/src/lib/domain/client/services/client_service.rs
- api/src/lib/domain/mediator/services/mediator_service.rs
- api/src/lib/infrastructure/repositories/client_repository.rs
- api/src/lib/infrastructure/repositories/realm_repository.rs
- front/src/api/api.interface.ts
* add update_client handler and route for updating client details
* introduce UpdateClientValidator for request validation
* extend ClientService and ClientRepository with update_client methods
* create UpdateClientDto for data transfer during client updates
* refactor client routes to include update_client endpoint
> feat: implement update client functionality

- api/src/lib/application/http/client/handlers/create_client.rs
- api/src/lib/application/http/client/handlers/update_client.rs
- api/src/lib/domain/client/ports/client_service.rs
- api/src/lib/domain/client/services/client_service.rs
- api/src/lib/domain/mediator/services/mediator_service.rs
* refactor create_client handler to utilize CreateClientDto for improved data handling
* enhance client creation process by integrating realm retrieval and random secret generation
* streamline imports in client service and mediator service for better organization
* remove CreateClientValidator from client service interface to simplify parameter handling
* update related services and handlers to accommodate new DTO structure
> refactor: update client creation logic and validation

- api/src/lib/application/http/client/handlers.rs
- api/src/lib/application/http/client/handlers/create_role.rs
- api/src/lib/application/http/client/handlers/get_client_roles.rs
- api/src/lib/application/http/client/router.rs
- api/src/lib/application/http/role/handlers.rs
- api/src/lib/application/http/role/handlers/update_role.rs
- api/src/lib/application/http/role/policies.rs
- api/src/lib/application/http/role/router.rs
- api/src/lib/application/http/role/validators.rs
- api/src/lib/application/url.rs
- api/src/lib/domain/role/entities.rs
- api/src/lib/domain/role/ports.rs
- api/src/lib/domain/role/services.rs
- api/src/lib/infrastructure/repositories/role_repository.rs
- front/src/api/api.interface.ts
- front/src/api/role.api.ts
- front/src/pages/role/columns/list-client.column.tsx
- front/src/pages/role/feature/page-role-settings-feature.tsx
- front/src/pages/role/ui/page-role-permissions.tsx
- front/src/pages/role/ui/page-role-settings.tsx
This pull request introduces significant changes to the backend and frontend to enhance role management capabilities. The most notable updates include the migration of client role creation logic to a new module, the addition of an "Update Role" feature, and improvements to API response handling and frontend integration for roles.
* Migrated `create_role` functionality from `role` to `client` handlers, including renaming `CreateRoleRoute` to `CreateClientRoleRoute` and updating associated paths and tags.
* Added a new `update_role` handler in `role/handlers/update_role.rs` to support role updates, including validations, permissions, and API response structures.
* Introduced `UpdateRoleDto` and `UpdateRoleValidator` to define the data structure and validation logic for updating roles. 
* …
> feat: enhance role domain

- Cargo.lock
- Cargo.toml
- api/Cargo.toml
- core/Cargo.toml
- operator/Cargo.toml
- operator/src/bin/crdgen.rs
> Improve workspace management

- front/src/components/ui/sidebar.tsx
- front/src/pages/client/feature/page-create-client-feature.tsx
Add client_id to feature creation request body
> fix: sidebar context imports and usage

- CONTRIBUTING.md
- front/src/App.css
- front/src/App.tsx
- front/src/api/api.client.ts
- front/src/api/core.interface.ts
- front/src/api/core.mapper.ts
- front/src/components/nav-configuration.tsx
- front/src/components/ui/select.tsx
- front/src/components/ui/tabs.tsx
- front/src/components/work-in-progress.tsx
- front/src/hooks/use-feature.ts
- front/src/lib/features.ts
- front/src/pages/realm/feature/page-realm-settings-feature.tsx
- front/src/pages/realm/feature/page-realm-settings-general-feature.tsx
- front/src/pages/realm/feature/page-realm-settings-login-feature.tsx
- front/src/pages/realm/feature/page-realm-settings-security-feature.tsx
- front/src/pages/realm/layouts/realm-settings-layout.tsx
- front/src/pages/realm/page-realm.tsx
- front/src/pages/realm/ui/page-realm-settings-general.tsx
- front/src/pages/realm/ui/page-realm-settings.tsx
- front/src/pages/realm/validators.ts
- front/src/pages/role/feature/page-role-users-feature.tsx
- front/src/pages/user/ui/page-user-overview.tsx
- front/src/routes/router.ts
- front/src/routes/sub-router/client.router.ts
- front/src/routes/sub-router/realm.router.ts
Added : 
- basic feature flag system
- frontend for realm setting page
Beware that this is only the frontend for the realm settings page
> feat(realms): adding frontend for realm settings

- front/src/components/ui/data-table.tsx
- front/src/pages/client/columns/list-client.column.tsx
> fix: translated french words

- core/src/domain/webhook/entities/webhook_payload.rs
- core/src/domain/webhook/ports.rs
- core/src/domain/webhook/services/webhook_notifier_service.rs
> feat: move to one thread and add dynamic payload under the webhook

- core/src/application/common/mod.rs
- core/src/application/common/permissions.rs
> refactor: add FerriskeyPolicy to FerriskeyService and implement
